### ISSUE TITLE
Anticlockwise rotation support

### ISSUE THREAD

**Issue by b-allard** [harjot-oberai/Croller#13]
Hi, 

Is it possible to add a variable to decide if the sens is clockwise or counterclockwise ?

Thanks in advance, 

Benjamin

**Comment by harjot-oberai** [comment]
I have added an attribute `anticlockwise` in `v1.0.6`. Just set this attribute to `true` and your wish will come true! 😄 

Comment here in case of any issues.

**Comment by b-allard** [comment]
Hi, 
Thanks for your quick response, 
After some tests, I have an issue with the anticlockwise , the primary and the secondary progress doesn't start and  doesn't at the same point :/ 


I attached a screenshot to help you. (The primary progress is the green one)
![screenshot_20171012-072130](https://user-images.githubusercontent.com/21167184/31480636-348a85c2-af1f-11e7-82c4-90b8bd009971.png)

My xml : 

```
 <com.sdsmdg.harjot.crollerTest.Croller
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true"
        android:focusable="true"
        app:back_circle_color="@android:color/white"
        app:indicator_color="#019a6b"
        app:indicator_width="20"
        app:is_continuous="true"
        app:anticlockwise="true"
        app:label_color="@android:color/black"
        app:label_size="0"
        app:main_circle_color="@android:color/white"
        app:max="25"
        app:progress="0"
        app:progress_primary_color="#019a6b"
        app:progress_primary_stroke_width="50"
        app:progress_secondary_color="#EEEEEE"
        app:progress_secondary_stroke_width="45"
        app:start_offset="215"
        app:sweep_angle="300" />
```
