### ISSUE TITLE
label text cutoff 

### ISSUE THREAD

**Issue by ericwan78** [harjot-oberai/Croller#15]
The widget seems to be cutting off the bottom edge of the label. The following screenshot, for example, shows "Sensivity" as "Sensitivitv". I used the same params used in the instructions. I tried adjusting the layout externally and failed to fix the issue. Your suggestions will be appreciated. 

![screen shot 2017-10-27 at 2 23 05 pm](https://user-images.githubusercontent.com/1550874/32119288-c2fabd68-bb22-11e7-9aa5-30a7565edbd1.png)

**Comment by dev-ritik** [comment]
Thanks for pointing that out.
We are looking into the matter and will soon update the library with relevant changes.
