### ISSUE TITLE
onProgressChanged constantly being called

### ISSUE THREAD

**Issue by PawelS96** [harjot-oberai/Croller#25]
It's being called all the time, dozens of times per second, even when I'm not doing anything to the croller.

**Comment by dev-ritik** [comment]
HI @PawelS96 

`onProgressChanged` is called when 

- one of the two listeners is attached to the Croller object AND
- `onDraw` method is called somehow.

Now `onDraw` might be called by

- the user while interacting with the Croller's layout OR
- the parent layout while arranging the children views

So, In your case, check if the parent is continously changing the position of its child or not!

**Comment by PawelS96** [comment]
I've redesigned my UI since the last time, moved crollers from an activity to multiple fragments and this problem somehow disappeared. Anyway, thank you for replying.
