### ISSUE TITLE
Prevent vertical scroll when interacting with custom view

### ISSUE THREAD

**Issue by usagitoneko97** [harjot-oberai/Croller#5]
After some experimental test, i found the following code will prevent vertical scroll when touching the Croller.
` @Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        if (getParent() != null && event.getAction() == MotionEvent.ACTION_DOWN) {
            getParent().requestDisallowInterceptTouchEvent(true);
        }
        return super.dispatchTouchEvent(event);
    }`

**Comment by harjot-oberai** [comment]
Thanks for the input, I have updated the code to pass all touch events outside the progress circle to the parent and whenever the touch events are within the progress circle, the parent is not allowed to intercept the touch events as per your code. Cheers!
