### ISSUE TITLE
setProgress not working

### ISSUE THREAD

**Issue by usagitoneko97** [harjot-oberai/Croller#6]
missing invalidate() in the setProgress function

**Comment by harjot-oberai** [comment]
OH! Don't know how I missed all those `invalidate()` calls. They have to be added to every `set` method. I will update this by tomorrow. Otherwise you can just create a pull request and I'll be happy to merge.

**Comment by zeetherocker** [comment]
As a temporary fix, I'm calling invalidate after setProgress() but this doesn't invoke the OnProgressChangeListener. Is it just me or its really not working?
