### ISSUE TITLE
Minimum value should be zero not one

### ISSUE THREAD

**Issue by Julisons** [harjot-oberai/Croller#8]
zero to help disable the knob

**Comment by Julisons** [comment]
is there a value that can be updated?

**Comment by ligi** [comment]
This also caused a WTF moment for me - a fix is easy but kinda ugly as it would be a breaking change ..

**Comment by harjot-oberai** [comment]
@Julisons @ligi : Updating the min value is possible, but it conflicts with my idea that the indicator on the knob should point to some value. If 0 is set as the min value, where will the indicator point when the progress is 0 ?

**Comment by Julisons** [comment]
i have seen a lot of knobs with a zero value and the indicator pointing at zero only allows it to be off. Am using this lib in my app and the zero value seems too important for my functionalities in the app.

**Comment by Julisons** [comment]
Or you can add it as a property i.e  app;minValue

**Comment by harjot-oberai** [comment]
I have added the `min` attribute. Just set its value to `0` for your desired functionality.
I have kept the default value as 1 though.
Cheers!
